### ISSUE TITLE
sbt-ensime 2.0.1 does not work with JDK9

### ISSUE THREAD

**Issue by akreuzer** [ensime/ensime-sbt#367] opened 2017-09-25 09:16 UTC
### Steps to reproduce

1. Install JDK9
2. Create an sbt project and add the sbt-ensime plugin
3. Run sbt

### Expected behaviour

sbt works

### Actual behaviour

```
java.io.FileNotFoundException: Could not automatically find the JDK/lib/tools.jar.
[error] You must explicitly set JDK_HOME or JAVA_HOME.
[error] 	at org.ensime.EnsimePlugin$.$anonfun$JdkDir$6(EnsimePlugin.scala:639)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at org.ensime.EnsimePlugin$.JdkDir$lzycompute(EnsimePlugin.scala:638)
[error] 	at org.ensime.EnsimePlugin$.JdkDir(EnsimePlugin.scala:626)
[error] 	at org.ensime.EnsimePlugin$.$anonfun$buildSettings$16(EnsimePlugin.scala:175)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at org.ensime.EnsimePlugin$.$anonfun$buildSettings$15(EnsimePlugin.scala:175)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[error] 	at java.base/java.lang.Thread.run(Thread.java:844)
[error] java.io.FileNotFoundException: Could not automatically find the JDK/lib/tools.jar.
```

Apparently the search for `tools.jar` is hardwired in `ensime-sbt/src/main/scala/EnsimePlugin.scala`.
However, `tools.jar` has been removed in JDK9, see [JDK9 migration guide](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-D867DCCC-CEB5-4AFA-9D11-9C62B7A3FAB1)

**Comment by fommil** [comment] 2017-09-27 07:49
there is also some logic in the server to search for jars under the `:jdk-home` and index them, and an assumption about where the `src.zip` lives, so Java 9 support will require work in multiple places.

I am unlikely to use Java 9 for some time, my advise is to work out what flags are needed to start Java 9 with the equivalent of `tools.jar` on the classpath and then do that: the server can be fixed later. The server uses the tools api in several places, it's not optional.

The docker images for building ensime 3.0 should probably be updated to include a cross build with java 9.

**Comment by smarter** [comment] 2017-09-27 19:26
@retronym wrote a tool to recreate rt.jar for Java 9, don't know if it could also work for tools.jar: https://github.com/retronym/java9-rt-export

**Comment by avdv** [comment] 2017-10-16 20:29
Hi.

I just had a look into this issue. FWIW, trying to start SBT in ensime-server, fails at `SensiblePlugin.scala` line 24:

```
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
	at java.base/java.lang.String.substring(String.java:1885)
	at fommil.SensiblePlugin$.<init>(SensiblePlugin.scala:24)
...
```
which happens because the value of the system property `java.version` simply is "9" for Java 9. 
```scala
  private val JavaSpecificFlags = sys.props("java.version").substring(0, 3) match {
    case "1.6" | "1.7" => List("-XX:MaxPermSize=256m")
    case _             => List("-XX:MaxMetaspaceSize=256m")
  }
```

**Comment by sarahgerweck** [comment] 2017-11-05 03:26
I'm also running into this. There's still a bit more to be done in other places, but Scala has reasonably good support for Java 9 now. Having the Ensime plugin loaded at all causes SBT to blow up on launch, even if you're not trying to run any Ensime-related tasks.

**Comment by yyadavalli** [comment] 2017-11-05 04:11
It is actually relatively easy to fix the plugin. But the bigger issue is the missing tools.jar, the server makes use of in mutiple places and cannot function without it. So even if you are able to use this plugin and create the `.ensime` file, we cannot run the server. 

@sarahgerweck I see your point in not blowing up sbt, the amount of work needed is low. The check for tools.jar need to be removed and a new cases for java9 have to be written where we are checking for java 1.7 and 1.8. Its a good issue for a contribution, if you are up for it.

**Comment by sarahgerweck** [comment] 2017-11-05 04:15
@yyadavalli I'll see if I can give it a shot. I think deferring any errors until you run an Ensime-related task would be a significant improvement, even if it doesn't fix the real issues.

**Comment by yyadavalli** [comment] 2017-11-05 04:26
@sarahgerweck Awesome, thanks. That's a good idea. I am not sure how to accomplish that given sbt's init structure. May be converting it to a task would delay running till needed, I mean the setting in question `ensimeJavaHome`.

**Comment by avdv** [comment] 2017-11-06 13:10
> @sarahgerweck the first problem is really in the sensible sbt Plugin where I could not even find the > sources in a repository somewhere. I guess @fommil has to fix this and publish a new version first...

Ditch that, my memory failed me here. That's only a problem in ensime-server...

**Comment by avdv** [comment] 2017-11-06 13:22
@sarahgerweck before you look into this more deeply, I had already made some first changes which might be helpful / avoid duplicate work. I have created a PR for you to look at, see #383

**Comment by yyadavalli** [comment] 2017-11-06 13:44
@avdv If you need the sources for sbt-sensible they are here https://gitlab.com/fommil/sbt-sensible @fommil should be open to a PR.

**Comment by fommil** [comment] 2017-11-06 16:17
this has not got anything to do with sbt-sensible. Also, the issue is about running ensime on java 9, not building ensime on java 9 (and I can guarantee you that this is the least of your troubles in that case)

**Comment by avdv** [comment] 2017-11-06 16:36
> @avdv If you need the sources for sbt-sensible they are here https://gitlab.com/fommil/sbt-sensible @fommil should be open to a PR.

Thanks! I just did open https://gitlab.com/fommil/sbt-sensible/merge_requests/17

**Comment by yyadavalli** [comment] 2017-11-06 16:40
@fommil I think there is an issue with how the java flags are set here
https://gitlab.com/fommil/sbt-sensible/blob/master/src/main/scala/SensiblePlugin.scala#L24

The substring errors out when loading sbt.

**Comment by fommil** [comment] 2017-11-06 17:17
@avdv thanks! But if you're trying to build ensime-sbt or ensime-server with java 9 it means you haven't set up `jenv` correctly. http://ensime.org/learning_scala/

**Comment by avdv** [comment] 2017-11-06 21:27
> @avdv thanks! But if you're trying to build ensime-sbt or ensime-server with java 9 it means you haven't set up jenv correctly. http://ensime.org/learning_scala/

That was by intention, really. I wanted to experiment with some things and try to get an idea what would be needed to get Java 9 support to ensime.

**Comment by fommil** [comment] 2017-11-06 21:44
ah! Cool, well I'll try to make an sbt-sensible release soon then. But you'll have a few other things to do to upgrade it.

**Comment by markehammons** [comment] 2018-03-02 00:28
edit: I had java_home pointing at jdk8, which may have been causing weirdness by itself with java9 as my java command

**Comment by fommil** [comment] 2018-03-22 22:42
fixed in 2.5.0... as you know, the server isn't tested with java 9 so we don't know

**Closed as completed by fommil** 2018-03-22 22:42 UTC

**Comment by AdmiralSnyder** [comment] 2018-04-16 13:37
This Problem occurs with java 10, too. so: should I open another issue?

**Comment by fommil** [comment] 2018-04-16 15:10
Only if you plan to fix it
