### ISSUE TITLE
Include sources for dependencies when the source code in not found in repos

### ISSUE THREAD

**Issue by clamus** [ensime/ensime-sbt#303] opened 2017-02-21 20:10 UTC
Is there a way to include source code for dependencies when the source code is not published in the corresponding maven repo, but the source code is in different location (either in local machine or other repo)? In this case, ensimeConfig prints a warning, but I would like to some how tell it where the source actually is.

**Comment by fommil** [comment] 2017-02-21 21:46
Closing because this is a question not a bug.

There should be an ensimeSourceDirs or something like that, or you could transform the ensimeConfig object with a transformer. I'm pretty sure the server just works, but I may be mistaken.

**Comment by fommil** [comment] 2017-02-21 21:46
Have a look through the keys at any rate and you might get some ideas.

**Closed as completed by fommil** 2017-02-21 21:46 UTC

**Comment by clamus** [comment] 2017-02-21 22:16
Thanks! The key is ensimeUnmanagedSourceArchives
